<?php

// The template availables in this module
function word_meaning_theme($existing, $type, $theme, $path) {
  return [
    'show-definitions' => [
      'variables' => ['meanings' => []],
    ],
    'search-definitions' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function word_meaning_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == 'word_meaning_form') {
    $form['#attached']['library'][] = 'word_meaning/jquery';
    $form['#attached']['library'][] = 'word_meaning/underscore';
    $form['#attached']['library'][] = 'word_meaning/backbone';
    $form['#attached']['library'][] = 'word_meaning/form';
  }
}
